/- Kernel dependency audit for the proof-derived manuscript ledger. -/

import BlackwellDilemma.PaperSemanticGate

namespace BlackwellDilemma.AxiomAudit

open BlackwellDilemma.Ledger
open BlackwellDilemma.PaperSemanticGate

#print axioms decompositionIdentityCore_proved
#print axioms topologicalLossOrderStatisticsAlgebraCore_proved
#print axioms topoClusterPartialCore_proved
#print axioms BlackwellDilemma.Infrastructure.part6LowerBoundTransferPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.topoGiantLossEnvelopePrinciple_proved
#print axioms PaperClaim.isClosed_eq_hasFullProof
#print axioms paperClaims_count
#print axioms paperClaimLabels_nodup
#print axioms completePaperKernelOnly_notYet
#print axioms claim_isClosed_iff_fullProofFlag
#print axioms completePaperKernelOnly_iff_all_claims_have_proofs
#print axioms completePaperKernelOnly_notYet_current
#print axioms paperClaimMachineLedgerGate

end BlackwellDilemma.AxiomAudit
