/- Kernel dependency audit for the proof-derived manuscript ledger. -/

import BlackwellDilemma.PaperSemanticGate

namespace BlackwellDilemma.AxiomAudit

open BlackwellDilemma.Ledger
open BlackwellDilemma.PaperSemanticGate

#print axioms decompositionIdentityCore_proved
#print axioms decompositionClaim_proved
#print axioms physicalIrreducibilityClaim_proved
#print axioms topologicalLossOrderStatisticsAlgebraCore_proved
#print axioms topoClusterPartialCore_proved
#print axioms BlackwellDilemma.Infrastructure.part6LowerBoundTransferPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.independentTrialAmplificationPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.part6DepthWitnessTransferPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.part6AnalyticKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.trapPrevalenceLocalKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.part6LocalPatternKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.separatedBlockPlacementPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.part6SeparatedPlacementKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.finiteTorusSeparatedSupportPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.part6FiniteTorusSupportKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.kappaStarClosedFormDivergencePrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.kappaStarClosedFormBoundsPrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.part6DepthGrowthKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.trapTreeBernoulliWelfarePrinciple_proved
#print axioms BlackwellDilemma.Infrastructure.errorCompoundingKernelBundle_proved
#print axioms BlackwellDilemma.Infrastructure.gaussianBridgeProbabilityPrinciple_proved
#print axioms errorCompoundingPartialCore_proved
#print axioms BlackwellDilemma.Infrastructure.topoGiantLossEnvelopePrinciple_proved
#print axioms PaperClaim.isClosed_eq_hasFullProof
#print axioms paperClaims_count
#print axioms paperClaimLabels_nodup
#print axioms completePaperKernelOnly_notYet
#print axioms claim_isClosed_iff_fullProofFlag
#print axioms completePaperKernelOnly_iff_all_claims_have_proofs
#print axioms completePaperKernelOnly_notYet_current
#print axioms paperClaimMachineLedgerGate
#print axioms BlackwellDilemma.IDPModel.no_revisit_persists_under_noBlocking
#print axioms BlackwellDilemma.IDPModel.exists_stopping_reachable
#print axioms BlackwellDilemma.IDPModel.stopping_welfare_le_oracle
#print axioms BlackwellDilemma.IDPModel.oracle_value_attainable
#print axioms BlackwellDilemma.IDPModel.reaches_openGraph_reachable
#print axioms BlackwellDilemma.IDPModel.relaxedOracleValue_le_globalValue
#print axioms BlackwellDilemma.IDPModel.oracleValue_le_relaxedOracleValue
#print axioms BlackwellDilemma.IDPModel.oracleValue_eq_relaxedOracleValue_of_attainable
#print axioms BlackwellDilemma.IDPModel.oracleValue_eq_relaxedOracleValue_iff_terminalComplete
#print axioms BlackwellDilemma.UnifiedWelfareSetup.unifiedDecompositionBundle_proved

end BlackwellDilemma.AxiomAudit
