#!/usr/bin/env python3
"""Render README formalisation status directly from Lean evaluation."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import Counter
from pathlib import Path


LEAN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = LEAN_ROOT.parent
INVENTORY = REPO_ROOT / "paper" / "claim_inventory.json"
ROOT_MODULE = LEAN_ROOT / "BlackwellDilemma.lean"
LEAN_README = LEAN_ROOT / "README.md"
ROOT_README = REPO_ROOT / "README.md"


def evaluated_claims() -> list[tuple[str, str, str]]:
    result = subprocess.run(
        ["lake", "env", "lean", "BlackwellDilemma/PaperSemanticGate.lean"],
        cwd=LEAN_ROOT,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stdout)
    return re.findall(
        r"paper_claim=([^|\s]+)\|"
        r"(closed|partial|conditional|refuted-encoding|unformalized)\|"
        r"(local|mixed|external-library|semantic-repair)",
        result.stdout,
    )


def formal_root_imports() -> list[str]:
    return re.findall(
        r"^import\s+([^\s]+)",
        ROOT_MODULE.read_text(encoding="utf-8"),
        re.MULTILINE,
    )


def render_lean_readme(
    claims: list[tuple[str, str, str]],
    metadata: dict[str, dict[str, object]],
    root_imports: list[str],
) -> str:
    counts = Counter(state for _label, state, _route in claims)
    rows = []
    for label, state, route in claims:
        item = metadata[label]
        rows.append(
            f"| `{label}` | {item['kind']} | {state} | {route} | {item['title']} |"
        )
    table = "\n".join(rows)
    return f"""<!-- GENERATED by scripts/render_paper_claim_readme.py; DO NOT EDIT. -->
# BlackwellDilemma Lean 4 formalisation

The manuscript inventory and every status below are produced from the evaluated
Lean proof ledger. A claim is closed only when its `ClaimEvidence` value is
`proved statement proof`; no editable status field exists.

## Machine state

```text
paper_claims_total={len(claims)}
paper_claims_closed={counts['closed']}
paper_claims_partial={counts['partial']}
paper_claims_conditional={counts['conditional']}
paper_claims_refuted_encoding={counts['refuted-encoding']}
paper_claims_unformalized={counts['unformalized']}
formal_root_imports={','.join(root_imports)}
```

| Label | Kind | State | Route | Title |
|---|---|---|---|---|
{table}

## Verification

```powershell
lake build BlackwellDilemma
lake build BlackwellDilemma.AxiomAudit
python scripts/audit_kernel_surface.py
python scripts/audit_conditional_surface.py
python scripts/audit_paper_semantic_gate.py
python scripts/audit_axiom_output.py
python scripts/render_paper_claim_readme.py --check
```

The canonical label inventory is `../paper/claim_inventory.json`. The formal
root imports only the proof-derived gate. The current kernel surface contains
no project axiom or proof escape, but only exact full-statement proof witnesses
count as paper closure.
"""


def render_root_section(claims: list[tuple[str, str, str]]) -> str:
    counts = Counter(state for _label, state, _route in claims)
    return f"""## Lean 4 Formalisation

<!-- BEGIN GENERATED PAPER CLAIM STATUS -->
This status is generated by evaluating the Lean proof ledger. A claim can be
closed only by a proof term of its complete stored proposition.

```text
total={len(claims)} closed={counts['closed']} partial={counts['partial']} conditional={counts['conditional']} refuted-encoding={counts['refuted-encoding']} unformalized={counts['unformalized']}
```

See [`lean4/README.md`](lean4/README.md) for the generated claim roster and
[`paper/claim_inventory.json`](paper/claim_inventory.json) for the manuscript
inventory.
<!-- END GENERATED PAPER CLAIM STATUS -->

"""


def root_with_generated_section(current: str, section: str) -> str:
    start = current.index("## Lean 4 Formalisation")
    end = current.index("## Installation")
    return current[:start] + section + current[end:]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    metadata = {claim["label"]: claim for claim in inventory["claims"]}
    claims = evaluated_claims()
    root_imports = formal_root_imports()
    labels = [label for label, _state, _route in claims]
    if labels != list(metadata):
        raise RuntimeError("Lean claim labels do not match claim_inventory.json")

    lean_text = render_lean_readme(claims, metadata, root_imports)
    root_text = root_with_generated_section(
        ROOT_README.read_text(encoding="utf-8"), render_root_section(claims)
    )

    stale = []
    if LEAN_README.read_text(encoding="utf-8") != lean_text:
        stale.append(str(LEAN_README.relative_to(REPO_ROOT)))
    if ROOT_README.read_text(encoding="utf-8") != root_text:
        stale.append(str(ROOT_README.relative_to(REPO_ROOT)))

    if args.check:
        print(f"generated_readmes_stale={len(stale)}")
        print("generated_readme_stale_paths=" + ",".join(stale))
        return 1 if stale else 0

    LEAN_README.write_text(lean_text, encoding="utf-8")
    ROOT_README.write_text(root_text, encoding="utf-8")
    print("generated_readmes_written=2")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
