#!/usr/bin/env python3
"""Render README formalisation status directly from Lean evaluation."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import Counter
from pathlib import Path


LEAN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = LEAN_ROOT.parent
INVENTORY = REPO_ROOT / "paper" / "claim_inventory.json"
PUBLICATION_LEDGER = REPO_ROOT / "paper" / "publication_evidence_ledger.json"
ROOT_MODULE = LEAN_ROOT / "BlackwellDilemma.lean"
LEAN_README = LEAN_ROOT / "README.md"
ROOT_README = REPO_ROOT / "README.md"


def evaluated_claims() -> list[tuple[str, str, str]]:
    build = subprocess.run(
        ["lake", "build", "BlackwellDilemma.PaperSemanticGate"],
        cwd=LEAN_ROOT,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if build.returncode != 0:
        raise RuntimeError(build.stdout)
    result = subprocess.run(
        ["lake", "env", "lean", "BlackwellDilemma/PaperSemanticGate.lean"],
        cwd=LEAN_ROOT,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stdout)
    return re.findall(
        r"paper_claim=([^|\s]+)\|"
        r"(closed|partial|conditional|refuted-encoding|unformalized)\|"
        r"(local|mixed|external-library|semantic-repair)",
        result.stdout,
    )


def formal_root_imports() -> list[str]:
    return re.findall(
        r"^import\s+([^\s]+)",
        ROOT_MODULE.read_text(encoding="utf-8"),
        re.MULTILINE,
    )


def render_lean_readme(
    claims: list[tuple[str, str, str]],
    metadata: dict[str, dict[str, object]],
    root_imports: list[str],
    publication_summary: dict[str, object],
) -> str:
    counts = Counter(state for _label, state, _route in claims)
    rows = []
    for label, state, route in claims:
        item = metadata[label]
        rows.append(
            f"| `{label}` | {item['kind']} | {state} | {route} | {item['title']} |"
        )
    table = "\n".join(rows)
    return f"""<!-- GENERATED by scripts/render_paper_claim_readme.py; DO NOT EDIT. -->
# BlackwellDilemma Lean 4 formalisation

The manuscript inventory and every status below are produced from the evaluated
Lean proof ledger. A claim is closed only when its `ClaimEvidence` value is
`proved statement proof`; no editable status field exists.

## Machine state

```text
paper_claims_total={len(claims)}
paper_claims_closed={counts['closed']}
paper_claims_partial={counts['partial']}
paper_claims_conditional={counts['conditional']}
paper_claims_refuted_encoding={counts['refuted-encoding']}
paper_claims_unformalized={counts['unformalized']}
formal_root_imports={','.join(root_imports)}
publication_evidence_closed={publication_summary['publication_evidence_closed']}
publication_obligations_passed={publication_summary['obligations_passed']}/{publication_summary['obligations_total']}
model_assumptions_admissible={publication_summary['model_assumptions_admissible']}/{publication_summary['model_assumptions_total']}
```

| Label | Kind | State | Route | Title |
|---|---|---|---|---|
{table}

## Verification

```powershell
lake build BlackwellDilemma
lake build BlackwellDilemma.AxiomAudit
python scripts/audit_kernel_surface.py
python scripts/audit_conditional_surface.py
python scripts/audit_paper_semantic_gate.py
python scripts/audit_axiom_output.py
python scripts/render_paper_claim_readme.py --check
python ../tools/verify_reference_registry.py
python ../tools/audit_publication_obligations.py --check-ledger
```

The canonical label inventory is `../paper/claim_inventory.json`. The formal
root imports only the proof-derived gate. The current kernel surface contains
no project axiom or proof escape, but only exact full-statement proof witnesses
count as paper closure.
"""


def render_root_readme(
    claims: list[tuple[str, str, str]],
    root_imports: list[str],
    publication_summary: dict[str, object],
) -> str:
    counts = Counter(state for _label, state, _route in claims)
    return f"""<!-- GENERATED by lean4/scripts/render_paper_claim_readme.py; DO NOT EDIT. -->
# The Blackwell Dilemma

**When Better Information Makes Agents Worse Off Under Endogenous Feasibility Constraints**

[SSRN 6478278](https://doi.org/10.2139/ssrn.6478278) | [Zenodo 10.5281/zenodo.19251487](https://doi.org/10.5281/zenodo.19251487)

Blackwell's theorem (1953) states that more informative signals lead to weakly better decisions. This project studies the boundary created by irreversible actions, topology-blind signals, and the two-dimensional bond-percolation threshold $p_c = 1/2$.

## Machine State

The status below is evaluated from the {len(claims)}-claim Lean ledger. Only a proof term
of a claim's complete stored proposition closes that claim.

```text
total={len(claims)} closed={counts['closed']} partial={counts['partial']} conditional={counts['conditional']} refuted-encoding={counts['refuted-encoding']} unformalized={counts['unformalized']}
formal_root_imports={','.join(root_imports)}
publication_evidence_closed={publication_summary['publication_evidence_closed']}
publication_obligations_passed={publication_summary['obligations_passed']}/{publication_summary['obligations_total']}
model_assumptions_admissible={publication_summary['model_assumptions_admissible']}/{publication_summary['model_assumptions_total']}
```

See [`lean4/README.md`](lean4/README.md) for the generated claim roster and
[`paper/claim_inventory.json`](paper/claim_inventory.json) for the manuscript
inventory.

## Verification

```powershell
cd lean4
lake build BlackwellDilemma
lake build BlackwellDilemma.AxiomAudit
python scripts/audit_paper_semantic_gate.py
python scripts/audit_axiom_output.py
python scripts/audit_kernel_surface.py
python scripts/render_paper_claim_readme.py --check
cd ..
python tools/verify_reference_registry.py
python tools/audit_publication_obligations.py --check-ledger
python tools/verify_public_evidence.py
python tracker.py --check-report
python verification/render_live_prediction_report.py --check
```

## Research Artifacts

- [`paper/prediction_note_public.pdf`](paper/prediction_note_public.pdf): public short paper.
- [`paper/prediction_note.tex`](paper/prediction_note.tex): short-paper source.
- [`prediction.md`](prediction.md): pre-registered prediction and falsification rule.
- [`verification/live_prediction_verification_2026-05-21.json`](verification/live_prediction_verification_2026-05-21.json): machine-readable verification result.
- [`verification/live_prediction_verification_2026-05-21.md`](verification/live_prediction_verification_2026-05-21.md): generated verification report.
- [`simulation/`](simulation/) and [`results/`](results/): simulations and committed outputs, including the FSS with critical exponent nu = 4/3 diagnostic.
- [`docs/`](docs/): computational appendix and public explorer.

## Installation

Python 3.9 or newer is required for the computational checks. Lean uses the
toolchain pinned in `lean4/lean-toolchain`.

```powershell
python -m venv .venv
.venv\\Scripts\\Activate.ps1
pip install -r requirements.txt
```

## Citation

```bibtex
@article{{li2026blackwell,
  title={{The Blackwell Dilemma: No Non-Vacuous Information Ordering Exists Under Endogenous Feasibility Constraints}},
  author={{Li, Alex Chengyu}},
  year={{2026}},
  doi={{10.5281/zenodo.19251487}}
}}
```

License: MIT.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    publication_ledger = json.loads(PUBLICATION_LEDGER.read_text(encoding="utf-8"))
    if publication_ledger.get("manuscript_sha256") != inventory.get("manuscript_sha256"):
        raise RuntimeError("publication evidence ledger does not match manuscript inventory")
    publication_summary = publication_ledger["summary"]
    metadata = {claim["label"]: claim for claim in inventory["claims"]}
    claims = evaluated_claims()
    root_imports = formal_root_imports()
    labels = [label for label, _state, _route in claims]
    if labels != list(metadata):
        raise RuntimeError("Lean claim labels do not match claim_inventory.json")

    lean_text = render_lean_readme(
        claims, metadata, root_imports, publication_summary
    )
    required_artifacts = [
        REPO_ROOT / "paper" / "prediction_note_public.pdf",
        REPO_ROOT / "paper" / "prediction_note.tex",
        REPO_ROOT / "prediction.md",
        REPO_ROOT / "verification" / "live_prediction_verification_2026-05-21.json",
        REPO_ROOT / "verification" / "live_prediction_verification_2026-05-21.md",
        REPO_ROOT / "simulation",
        REPO_ROOT / "results",
        REPO_ROOT / "docs",
    ]
    missing_artifacts = [str(path) for path in required_artifacts if not path.exists()]
    if missing_artifacts:
        raise RuntimeError("missing README artifacts: " + ",".join(missing_artifacts))

    root_text = render_root_readme(claims, root_imports, publication_summary)

    stale = []
    if LEAN_README.read_text(encoding="utf-8") != lean_text:
        stale.append(str(LEAN_README.relative_to(REPO_ROOT)))
    if ROOT_README.read_text(encoding="utf-8") != root_text:
        stale.append(str(ROOT_README.relative_to(REPO_ROOT)))

    if args.check:
        print(f"generated_readmes_stale={len(stale)}")
        print("generated_readme_stale_paths=" + ",".join(stale))
        return 1 if stale else 0

    LEAN_README.write_text(lean_text, encoding="utf-8")
    ROOT_README.write_text(root_text, encoding="utf-8")
    print("generated_readmes_written=2")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
