#!/usr/bin/env python3
"""Reject unclassified or manually mutable repository documentation."""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

GENERATED_DOCUMENTS = {
    "README.md":
        "<!-- GENERATED by lean4/scripts/render_paper_claim_readme.py; DO NOT EDIT. -->",
    "lean4/README.md":
        "<!-- GENERATED by scripts/render_paper_claim_readme.py; DO NOT EDIT. -->",
    "prediction_status.md":
        "<!-- GENERATED by tracker.py --report; DO NOT EDIT. -->",
    "verification/live_prediction_verification_2026-05-21.md":
        "<!-- GENERATED by verification/verify_live_prediction.py; DO NOT EDIT. -->",
}

IMMUTABLE_RESEARCH_OBJECTS = {
    "prediction.md": "df6f587151600cb191037e837f5b3984878196382deef20bc0154a7bdcb2d39e",
}

EXPECTED_MARKDOWN = set(GENERATED_DOCUMENTS) | set(IMMUTABLE_RESEARCH_OBJECTS)
IGNORED_DIRS = {".git", ".lake", "__pycache__"}


def fail(message: str) -> None:
    print(f"documentation_surface_error={message}", file=sys.stderr)
    raise SystemExit(1)


def repository_markdown() -> set[str]:
    paths: set[str] = set()
    for path in ROOT.rglob("*.md"):
        relative = path.relative_to(ROOT)
        if any(part in IGNORED_DIRS for part in relative.parts):
            continue
        paths.add(relative.as_posix())
    return paths


def tracked_markdown() -> set[str]:
    result = subprocess.run(
        ["git", "ls-files", "--", "*.md"],
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    return {line.strip().replace("\\", "/") for line in result.stdout.splitlines()
            if line.strip()}


def require_exact_roster(actual: set[str], source: str) -> None:
    missing = sorted(EXPECTED_MARKDOWN - actual)
    extra = sorted(actual - EXPECTED_MARKDOWN)
    if missing or extra:
        fail(f"{source}:missing={','.join(missing)}:extra={','.join(extra)}")


def require_ci_commands() -> None:
    lean_workflow = (ROOT / ".github/workflows/lean_ci.yml").read_text(encoding="utf-8")
    evidence_workflow = (ROOT / ".github/workflows/evidence_ci.yml").read_text(
        encoding="utf-8"
    )
    required = {
        "lean_readmes": (
            lean_workflow,
            "python scripts/render_paper_claim_readme.py --check",
        ),
        "lean_documentation_surface": (
            lean_workflow,
            "python ../tools/audit_documentation_surface.py",
        ),
        "prediction_status": (
            evidence_workflow,
            "python tracker.py --check-report",
        ),
        "live_prediction_report": (
            evidence_workflow,
            "python verification/render_live_prediction_report.py --check",
        ),
        "public_documentation_surface": (
            evidence_workflow,
            "python tools/audit_documentation_surface.py",
        ),
    }
    missing = [name for name, (text, command) in required.items() if command not in text]
    if missing:
        fail("missing-ci-command:" + ",".join(missing))


def main() -> None:
    require_exact_roster(repository_markdown(), "filesystem")
    require_exact_roster(tracked_markdown(), "git")

    for relative, marker in GENERATED_DOCUMENTS.items():
        text = (ROOT / relative).read_text(encoding="utf-8")
        if not text.startswith(marker):
            fail(f"generated-marker:{relative}")

    for relative, expected_hash in IMMUTABLE_RESEARCH_OBJECTS.items():
        canonical_bytes = (ROOT / relative).read_bytes().replace(b"\r\n", b"\n")
        actual_hash = hashlib.sha256(canonical_bytes).hexdigest()
        if actual_hash != expected_hash:
            fail(f"immutable-hash:{relative}:{actual_hash}")

    require_ci_commands()
    print(f"documentation_markdown_total={len(EXPECTED_MARKDOWN)}")
    print(f"documentation_generated={len(GENERATED_DOCUMENTS)}")
    print(f"documentation_immutable_research_objects={len(IMMUTABLE_RESEARCH_OBJECTS)}")
    print("documentation_unclassified=0")
    print("documentation_manual_status_files=0")


if __name__ == "__main__":
    main()
