name = "BlackwellDilemma"
version = "1.3.5"
keywords = ["economics", "decision-theory", "information-theory", "percolation"]
defaultTargets = ["BlackwellDilemma"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "BlackwellDilemma"
